title: DevLog
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://sodapapa.github.io
baseurl: '/myBlog'
paginate_path: "/page:num/"
permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-toc

paginate: 7

navigation:
  - title: Home
    url: /index.html

  - title: About
    url: /about

  - title: Contact
    url: /contact

social:
  github: 415hdh
  twitter: 415hdh
  facebook: 415hdh
  email: 415hdh@gmail.com

google_analytics: "UA-164167126-1"

disqus_shortname: 'sodapapa-github-io'
disqus: sodapapa-github-io



toc_title: Table of contents on this page
